### PR TITLE
Generic updates and improvements

### PR DESCRIPTION
**Pull request by matyaskuti**
There is a relatively large number of commits as the changes were done incrementally, but the main changes in the PR are the following:

* Cookiecutter major version update
* GitHub actions CI
* Dependabot config
* Add isort
* Make mypy non-optional and strict
* Metadata update

### CODE REVIEW

**Comment by matyaskuti** [comment]
@udh-mendix if you could take a look, that'd be great 🙂

**Comment by udh-mendix** [comment]
@matyaskuti looks good to me, one question about pylint - why not make that mandatory as well?

**Comment by matyaskuti** [comment]
@udh-mendix I wasn't sure about `pylint` yet, so I didn't touch that. I'm planning some more changes in the near future and want to explore other tools (eg. [ruff](https://github.com/astral-sh/ruff)) as well.

**Review by udh-mendix — APPROVED** [review]

**Comment by matyaskuti** [comment]
@jeohist could you merge?

**Pull request merged**
